export const times = {
  open: '19:00',
  close: '02:00',
};

export const storeInfo = {
  id: 'big-burguer-lanches',
  slug: 'big-burguer-lanches',
  name: 'Big Burguer Lanches',
  tagline: 'Os melhores hambúrgueres e batatas da cidade!',
  phone: '5511999999999',
  address: 'Rua dos Cardápios, 111',
  logo: '/logo.svg',
  cover: '/logo.svg',
  hours: [
    { day: 0, open: '19:00', close: '02:00', closed: false },
    { day: 1, open: '19:00', close: '02:00', closed: true },
    { day: 2, open: '19:00', close: '02:00', closed: false },
    { day: 3, open: '19:00', close: '02:00', closed: false },
    { day: 4, open: '19:00', close: '02:00', closed: false },
    { day: 5, open: '19:00', close: '02:00', closed: false },
    { day: 6, open: '19:00', close: '02:00', closed: false },
  ],
  regions: [
    { id: 1, name: 'Centro', fee: 5.5 },
    { id: 2, name: 'Bairro Novo', fee: 8.5 },
  ],
  payments: ['Pix', 'Cartão de crédito', 'Cartão de débito', 'Dinheiro'],
  minOrder: 25,
  acceptsPickup: true,
  acceptsDelivery: true,
  orderMessage: 'Pedido enviado, aguardando confirmação do estabelecimento.',
  deliveryFee: 5.5,
  troco: '',
  banners: [
    {
      image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1200&q=80',
      title: 'BURGERS ARTESANAIS',
      ctaLabel: 'Ver cardápio',
      targetCategoryId: 'burgers',
    },
  ],
};

export const HeaderCard = [
  { id: 1, name: 'Entrega', tagline: 'Em sua região.' },
  { id: 2, name: 'Retirada', tagline: 'No balcão.' },
  { id: 3, name: 'Pedido mínimo', tagline: 'R$ 25,00' },
];

export const categories = [
  { id: 'burgers', name: 'Burgers' },
  { id: 'combos', name: 'Combos' },
  { id: 'porcoes', name: 'Porções' },
  { id: 'bebidas', name: 'Bebidas' },
];

export const products = [
  {
    id: 1,
    category: 'burgers',
    name: 'X-Bacon',
    description: 'Pão artesanal, hambúrguer, queijo, bacon e molho da casa.',
    price: 28.9,
    ingredients: ['Pão', 'Hambúrguer', 'Queijo', 'Bacon'],
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80',
    featured: true,
  },
  {
    id: 2,
    category: 'burgers',
    name: 'X-Salada',
    description: 'Hambúrguer, queijo, alface, tomate e molho especial.',
    price: 26.9,
    ingredients: ['Pão', 'Hambúrguer', 'Queijo', 'Alface'],
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=80',
    featured: true,
  },
  {
    id: 3,
    category: 'combos',
    name: 'Combo Big',
    description: 'X-Bacon + batata média + refrigerante lata.',
    price: 36.9,
    ingredients: ['X-Bacon', 'Batata', 'Refrigerante'],
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80',
    featured: true,
  },
  {
    id: 4,
    category: 'porcoes',
    name: 'Batata Frita',
    description: 'Porção crocante de batata com sal grosso.',
    price: 18.9,
    ingredients: ['Batata', 'Sal'],
    image: 'https://images.unsplash.com/photo-1576107232684-1279f390859f?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 5,
    category: 'bebidas',
    name: 'Refrigerante Lata',
    description: 'Escolha entre cola, limão, guaraná ou uva.',
    price: 7.5,
    ingredients: ['Refrigerante'],
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f2b7420e?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 6,
    category: 'combos',
    name: 'Combo Família',
    description: 'Dois hambúrgueres, batata grande e 4 refris.',
    price: 55.8,
    ingredients: ['Dois hambúrgueres', 'Batata grande', 'Refrigerante'],
    image: 'https://images.unsplash.com/photo-1550317138-10000687a72b?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 7,
    category: 'porcoes',
    name: 'Onion Rings',
    description: 'Anéis de cebola empanados e crocantes.',
    price: 19.5,
    ingredients: ['Cebola', 'Empanado'],
    image: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 8,
    category: 'bebidas',
    name: 'Água Mineral',
    description: '500 ml, gelada e natural.',
    price: 5.0,
    ingredients: ['Água'],
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 9,
    category: 'burgers',
    name: 'Duplo Smash',
    description: 'Dois hambúrgueres, queijo cheddar e molho da casa.',
    price: 31.5,
    ingredients: ['Dois hambúrgueres', 'Queijo', 'Molho'],
    image: 'https://images.unsplash.com/photo-1534790566855-4cb788d389ec?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 10,
    category: 'combos',
    name: 'Combo Casal',
    description: 'Dois hambúrgueres, porção e 2 refris.',
    price: 44.9,
    ingredients: ['Dois hambúrgueres', 'Porção', '2 refrigerantes'],
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=80',
  },
];
